export type Product = {
  id: string;
  slug: string;
  name: string;
  subtitle: string;
  price: number;
  flavors: string[];
  imagePath: string;
};

export const products: Product[] = [
  {
    id: "mega-v2-10-packs",
    slug: "mega-v2-10-packs",
    name: "Mega V2 — 10 Packs",
    subtitle: "25 flavor options",
    price: 35,
    flavors: [
      "red bull",
      "red apple",
      "frozen tangerine",
      "mega melons",
      "Pineapple ice",
      "Frozen blue razz",
      "Frozen peach",
      "Zero nicotine disposable pods",
      "Strawberry banana",
      "Cotton candy",
      "Strawberry and cream",
      "Frozen cranberry lemon",
      "Guava ice",
      "Frozen lychee ice",
      "Blue razz",
      "Mixed berry ice",
      "Grape",
      "Strawberry mint",
      "Clear ice",
      "Cherry cola",
      "Watermelon mint",
      "Frozen grape",
      "Smooth tobacco",
      "Cool mint",
      "clear 5 percent",
    ],
    imagePath: "/products/mega-v2-10-packs.jpg",
  },
  {
    id: "adalya-5-pieces-20000-puffs",
    slug: "adalya-5-pieces-20000-puffs",
    name: "Adalya — 5 Pieces / 20000 Puffs",
    subtitle: "16 flavor options",
    price: 35,
    flavors: [
      "blueberry",
      "Mi amor",
      "Grape mint",
      "Skyfall",
      "Mint point",
      "Love 66",
      "Lady killer",
      "Orange lemonade",
      "Peach ice",
      "Menthol",
      "Passionfruit guava kiwi",
      "Punk man",
      "Blue min",
      "Angel lips",
      "delons",
      "English lord",
    ],
    imagePath: "/products/adalya-5-pieces-20000-puffs.jpg",
  },
  {
    id: "fume-extra",
    slug: "fume-extra",
    name: "Fume Extra",
    subtitle: "16 flavor options",
    price: 25,
    flavors: [
      "blueberry cc",
      "Strawberry",
      "Bubblegum",
      "Paradise",
      "Desert breeze",
      "Hawaii juice",
      "Mango",
      "Banana ice",
      "clear",
      "Melon ice",
      "Gummy bears",
      "Strawberry banana",
      "Fresh lychee",
      "Double apple",
      "Unicorn",
      "mint ice",
    ],
    imagePath: "/products/fume-extra.webp",
  },
  {
    id: "lava-plus",
    slug: "lava-plus",
    name: "Lava Plus",
    subtitle: "22 flavor options",
    price: 30,
    flavors: [
      "clear ice",
      "Strawberry watermelon bubblegum",
      "Berry mist",
      "Jolly rancher ice",
      "Watermelon mint",
      "Pineapple, coconut rum",
      "Bloom",
      "Fruit blast",
      "Black ice",
      "Havana tobacco",
      "Mango ice",
      "Strawberry lemonade",
      "Guava ice banana milkshake",
      "Peach mango watermelon",
      "Strawberry quake",
      "Banana milkshake",
      "Sour patch",
      "Dragon flume",
      "Sour watermelon candy",
      "Mojito",
      "Fruit ice",
      "cool mint",
      "peach ice",
    ],
    imagePath: "/products/lava-plus.webp",
  },
  {
    id: "stig",
    slug: "stig",
    name: "Stig",
    subtitle: "1 flavor option",
    price: 25,
    flavors: ["green apple"],
    imagePath: "/products/stig.png",
  },
  {
    id: "geek-bars-pulse-x",
    slug: "geek-bars-pulse-x",
    name: "Geek Bars Pulse X",
    subtitle: "14 flavor options",
    price: 30,
    flavors: [
      "Miami MINT",
      "Mexican mango",
      "Strawberry b pop",
      "Lime berry orange",
      "Clear diamond",
      "Clear ice",
      "Banana taffy freeze",
      "Watermelon ice",
      "Sour apple ice",
      "Virginia tobacco",
      "Blue razz ice",
      "White peach raspberry",
      "Banana taffy",
      "Sour mango pineapple",
    ],
    imagePath: "/products/geek-bars-pulse-x.jpg",
  },
  {
    id: "geek-x-mega",
    slug: "geek-x-mega",
    name: "Geek X Mega",
    subtitle: "12 flavor options",
    price: 30,
    flavors: [
      "clear",
      "Strawberry mango ice",
      "Strawberry kiwi ice",
      "Strawberry ice",
      "Cinnamon",
      "Cool mint",
      "Blue razz ice",
      "Cherry lemon breeze",
      "Tobacco",
      "Blackberry b pop",
      "Raspberry jam",
      "Miami mint",
      "Watermelon ice",
    ],
    imagePath: "/products/geek-x-mega.png",
  },
  {
    id: "myle-mini-box-1500-puffs",
    slug: "myle-mini-box-1500-puffs",
    name: "Myle Mini Box — 1500 Puffs",
    subtitle: "10 flavor options",
    price: 25,
    flavors: [
      "Cubano",
      "Strawberry watermelon",
      "Ice blueberry",
      "Red apple",
      "Prime pear",
      "Iced apple",
      "Sweet to",
      "Grape ice",
      "Peach ice",
      "Ice watermelon",
    ],
    imagePath: "/products/myle-mini-box-1500-puffs.webp",
  },
  {
    id: "mini-myle",
    slug: "mini-myle",
    name: "Mini Myle",
    subtitle: "7 flavor options",
    price: 25,
    flavors: [
      "ice Leche",
      "Raspberry watermelon",
      "Tobacco gold",
      "Ice blueberry",
      "Pink lemonade",
      "Peach ice",
      "Lemon mint",
    ],
    imagePath: "/products/mini-myle.jpg",
  },
];
